services:
  - type: web
    name: fastapi-gp-app
    env: python
    region: oregon  # or frankfurt/singapore
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install .
    startCommand: uvicorn app.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gp-database
          property: connectionString
      - key: DATABASE_URL_ASYNC
        fromDatabase:
          name: gp-database  
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0  # Match your requires-python
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: gp-database
    databaseName: gp_db
    user: joo
    plan: free
    region: oregon  # Must match service region!